import { defineTextMap, defaultText } from "../../i18n/textMap";

export const acceptInvitationPageText = defineTextMap({
  fr: { eyebrow: "VOTRE INVITATION", title: "Rejoignez la conversation.", invitationFor: "Votre invitation est destinée à", invitationSeparator: ". ", choosePassword: "Choisissez un mot de passe pour créer votre compte.", password: "Mot de passe", passwordHint: "Au moins 12 caractères", confirmation: "Confirmer le mot de passe", remember: "Se souvenir de moi pendant 30 jours", submit: "Créer le compte", submitting: "Création du compte…", invalidInvitation: "Cette invitation est invalide ou a expiré.", passwordMismatch: "Les mots de passe ne correspondent pas.", invalidPassword: "Le mot de passe doit contenir entre 12 et 1 024 caractères.", genericError: "Une erreur est survenue. Veuillez réessayer." },
  de: { eyebrow: "IHRE EINLADUNG", title: "Nehmen Sie am Gespräch teil.", invitationFor: "Ihre Einladung gilt für", invitationSeparator: ". ", choosePassword: "Wählen Sie ein Passwort, um Ihr Konto zu erstellen.", password: "Passwort", passwordHint: "Mindestens 12 Zeichen", confirmation: "Passwort bestätigen", remember: "30 Tage angemeldet bleiben", submit: "Konto erstellen", submitting: "Konto wird erstellt…", invalidInvitation: "Diese Einladung ist ungültig oder abgelaufen.", passwordMismatch: "Die Passwörter stimmen nicht überein.", invalidPassword: "Das Passwort muss zwischen 12 und 1.024 Zeichen enthalten.", genericError: "Ein Fehler ist aufgetreten. Bitte erneut versuchen." },
  it: { eyebrow: "IL TUO INVITO", title: "Unisciti alla conversazione.", invitationFor: "Il tuo invito è destinato a", invitationSeparator: ". ", choosePassword: "Scegli una password per creare il tuo account.", password: "Password", passwordHint: "Almeno 12 caratteri", confirmation: "Conferma password", remember: "Ricordami per 30 giorni", submit: "Crea account", submitting: "Creazione account…", invalidInvitation: "Questo invito non è valido o è scaduto.", passwordMismatch: "Le password non corrispondono.", invalidPassword: "La password deve contenere tra 12 e 1.024 caratteri.", genericError: "Si è verificato un errore. Riprova." },
  en: { eyebrow: "YOUR INVITATION", title: "Join the conversation.", invitationFor: "Your invitation is for", invitationSeparator: ". ", choosePassword: "Choose a password to create your account.", password: "Password", passwordHint: "At least 12 characters", confirmation: "Confirm password", remember: "Remember me for 30 days", submit: "Create account", submitting: "Creating account…", invalidInvitation: "This invitation is invalid or expired.", passwordMismatch: "The passwords do not match.", invalidPassword: "The password must contain between 12 and 1,024 characters.", genericError: "Something went wrong. Please try again." },
});

export const acceptInvitationPageDefaultText = defaultText(acceptInvitationPageText);
