import { defaultText, defineTextMap } from "../../i18n/textMap";

export const landingPageText = defineTextMap({
  fr: {
    brand: "Philo Genève",
    skipToContent: "Aller au contenu",
    navigationLabel: "Navigation principale",
    program: "Programme",
    about: "À propos",
    archives: "Archives",
    memberSpace: "Espace membre",
    eyebrow: "Association de philosophie · Genève",
    titleLineOne: "Penser",
    titleLineTwo: "ensemble.",
    introduction: "Un espace public pour éprouver les idées, déplacer les regards et faire vivre la philosophie dans la cité.",
    discover: "Découvrir le programme",
  },
  de: {
    brand: "Philo Genf",
    skipToContent: "Zum Inhalt springen",
    navigationLabel: "Hauptnavigation",
    program: "Programm",
    about: "Über uns",
    archives: "Archiv",
    memberSpace: "Mitgliederbereich",
    eyebrow: "Philosophischer Verein · Genf",
    titleLineOne: "Gemeinsam",
    titleLineTwo: "denken.",
    introduction: "Ein öffentlicher Raum, um Ideen zu prüfen, Perspektiven zu verschieben und Philosophie in der Stadt lebendig zu halten.",
    discover: "Programm entdecken",
  },
  it: {
    brand: "Philo Ginevra",
    skipToContent: "Vai al contenuto",
    navigationLabel: "Navigazione principale",
    program: "Programma",
    about: "Chi siamo",
    archives: "Archivio",
    memberSpace: "Area membri",
    eyebrow: "Associazione di filosofia · Ginevra",
    titleLineOne: "Pensare",
    titleLineTwo: "insieme.",
    introduction: "Uno spazio pubblico per mettere alla prova le idee, cambiare prospettiva e far vivere la filosofia nella città.",
    discover: "Scopri il programma",
  },
  en: {
    brand: "Philo Geneva",
    skipToContent: "Skip to content",
    navigationLabel: "Main navigation",
    program: "Programme",
    about: "About",
    archives: "Archive",
    memberSpace: "Member space",
    eyebrow: "Philosophy association · Geneva",
    titleLineOne: "Thinking",
    titleLineTwo: "together.",
    introduction: "A public space to test ideas, shift perspectives, and keep philosophy alive in the city.",
    discover: "Explore the programme",
  },
});

export const landingPageDefaultText = defaultText(landingPageText);
