import { defineTextMap } from "../../i18n/textMap";

export const eventPageText = defineTextMap({
  fr: {
    brand: "Groupe Genevois de Philosophie — accueil",
    back: "Retour à l’accueil",
    loading: "Chargement de la rencontre",
    notFoundTitle: "Rencontre introuvable",
    notFoundBody: "Cette rencontre n’existe pas ou n’est pas accessible au public.",
    event: "Rencontre",
    cancelled: "Annulée",
    participants: "Participant·es",
    date: "Date",
    location: "Lieu",
    address: "Adresse",
    online: "En ligne",
    cycle: "Cycle",
  },
  de: {
    brand: "Genfer Philosophische Gesellschaft — Startseite",
    back: "Zurück zur Startseite",
    loading: "Veranstaltung wird geladen",
    notFoundTitle: "Veranstaltung nicht gefunden",
    notFoundBody: "Diese Veranstaltung existiert nicht oder ist nicht öffentlich zugänglich.",
    event: "Veranstaltung",
    cancelled: "Abgesagt",
    participants: "Teilnehmende",
    date: "Datum",
    location: "Ort",
    address: "Adresse",
    online: "Online",
    cycle: "Zyklus",
  },
  it: {
    brand: "Gruppo Ginevrino di Filosofia — home",
    back: "Torna alla home",
    loading: "Caricamento dell’incontro",
    notFoundTitle: "Incontro non trovato",
    notFoundBody: "Questo incontro non esiste o non è accessibile al pubblico.",
    event: "Incontro",
    cancelled: "Annullato",
    participants: "Partecipanti",
    date: "Data",
    location: "Luogo",
    address: "Indirizzo",
    online: "Online",
    cycle: "Ciclo",
  },
  en: {
    brand: "Geneva Philosophy Group — home",
    back: "Back to home",
    loading: "Loading event",
    notFoundTitle: "Event not found",
    notFoundBody: "This event does not exist or is not publicly accessible.",
    event: "Event",
    cancelled: "Cancelled",
    participants: "Participants",
    date: "Date",
    location: "Venue",
    address: "Address",
    online: "Online",
    cycle: "Cycle",
  },
});
